[package]
name = "appcui"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
EnumBitFlags = "1.0.7"
chrono = "0.4.38"
AppCUIProcMacro = {path = "../appcui-proc-macro"}
fomat-macros = "0.3.2"

[target.'cfg(target_os = "linux")'.dependencies]
copypasta = "0.10.1"
libc = "0.2"


[features]
default = []
DEBUG_SHOW_WINDOW_TITLE_BOUNDERIES = []
EVENT_RECORDER = []

[lints]
workspace = true
